INSERT INTO permission VALUES('ROLE_ADMIN');
INSERT INTO permission VALUES('ROLE_ROOT');
INSERT INTO permission VALUES('ROLE_PRODUCTS_WRITE');
INSERT INTO permission VALUES('ROLE_PRODUCTS_READ');
INSERT INTO permission VALUES('ROLE_UNITS_READ');
INSERT INTO permission VALUES('ROLE_UNITS_WRITE');
INSERT INTO permission VALUES('ROLE_SUPPLIERS_READ');
INSERT INTO permission VALUES('ROLE_SUPPLIERS_WRITE');
INSERT INTO permission VALUES('ROLE_PURCHASE_REQUESTS_READ');
INSERT INTO permission VALUES('ROLE_PURCHASE_REQUESTS_READ_ALL');
INSERT INTO permission VALUES('ROLE_PURCHASE_REQUESTS_WRITE');
INSERT INTO permission VALUES('ROLE_APPROVALS_READ');
INSERT INTO permission VALUES('ROLE_APPROVALS_WRITE');
INSERT INTO permission VALUES('ROLE_QUOTATIONS_READ');
INSERT INTO permission VALUES('ROLE_QUOTATIONS_WRITE');
INSERT INTO permission VALUES('ROLE_QUOTATION_APPROVALS_READ');
INSERT INTO permission VALUES('ROLE_QUOTATION_APPROVALS_WRITE');
INSERT INTO permission VALUES('ROLE_PURCHASE_ORDERS_READ');
INSERT INTO permission VALUES('ROLE_PURCHASE_ORDERS_WRITE');
INSERT INTO permission VALUES('ROLE_PURCHASE_ORDERS_COMPETENCIES_WRITE');
INSERT INTO permission VALUES('ROLE_PURCHASE_ORDERS_WRITE_ROOT');
INSERT INTO permission VALUES('ROLE_ENTRIES_READ');
INSERT INTO permission VALUES('ROLE_ENTRIES_WRITE');
INSERT INTO permission VALUES('ROLE_COST_CENTERS_READ');
INSERT INTO permission VALUES('ROLE_COST_CENTERS_WRITE');
INSERT INTO permission VALUES('ROLE_PAYMENT_CONDITIONS_READ');
INSERT INTO permission VALUES('ROLE_PAYMENT_CONDITIONS_WRITE');
INSERT INTO permission VALUES('ROLE_DELIVERY_ADDRESSES_READ');
INSERT INTO permission VALUES('ROLE_DELIVERY_ADDRESSES_WRITE');
INSERT INTO permission VALUES('ROLE_BRANCH_OFFICES_READ');
INSERT INTO permission VALUES('ROLE_BRANCH_OFFICES_WRITE');
INSERT INTO permission VALUES('ROLE_LOCATIONS_READ');
INSERT INTO permission VALUES('ROLE_LOCATIONS_WRITE');
INSERT INTO permission VALUES('ROLE_PROJECTS_READ');
INSERT INTO permission VALUES('ROLE_PROJECTS_WRITE');

INSERT INTO permission VALUES('ROLE_NOTIFICATIONS');
INSERT INTO permission VALUES('ROLE_NOTIFICATIONS_NEW_QUOTATION_APPROVAL');
INSERT INTO permission VALUES('ROLE_NOTIFICATIONS_EVALUATE_QUOTATION_APPROVAL');
INSERT INTO permission VALUES('ROLE_NOTIFICATIONS_EVALUATE_PURCHASE_REQUEST_APPROVAL');
INSERT INTO permission VALUES('ROLE_NOTIFICATIONS_RECEIVE_PURCHASE_ORDER_ITEMS');

INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (1, NOW(), NOW(), 'AC', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (2, NOW(), NOW(), 'AL', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (3, NOW(), NOW(), 'AM', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (4, NOW(), NOW(), 'AP', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (5, NOW(), NOW(), 'BA', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (6, NOW(), NOW(), 'CE', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (7, NOW(), NOW(), 'DF', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (8, NOW(), NOW(), 'ES', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (9, NOW(), NOW(), 'GO', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (10, NOW(), NOW(), 'MA', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (11, NOW(), NOW(), 'MT', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (12, NOW(), NOW(), 'MS', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (13, NOW(), NOW(), 'MG', 'MG', 18);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (14, NOW(), NOW(), 'PA', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (15, NOW(), NOW(), 'PB', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (16, NOW(), NOW(), 'PR', 'MG', 7);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (17, NOW(), NOW(), 'PE', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (18, NOW(), NOW(), 'PI', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (19, NOW(), NOW(), 'RN', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (20, NOW(), NOW(), 'RS', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (21, NOW(), NOW(), 'RJ', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (22, NOW(), NOW(), 'RO', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (23, NOW(), NOW(), 'RR', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (24, NOW(), NOW(), 'SC', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (25, NOW(), NOW(), 'SP', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (26, NOW(), NOW(), 'SE', 'MG', 12);
INSERT INTO taxes(id, createddate, lastmodifieddate, statefrom, stateto, icms) VALUES (27, NOW(), NOW(), 'TO', 'MG', 12);

INSERT INTO settings("id", createddate, lastmodifieddate, "key", "value") VALUES (1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'MINIMAL_QUANTITY_TO_AUTO_APPROVE_QUOTATION', '3000');